#!/bin/bash

additional_gradle_tasks="
:apps:shared:licensee
testDebugUnitTest
:konsist:test
"

args=""
for arg in "$@"; do
  if [ "$arg" == "--lite" ]; then
    additional_gradle_tasks=""
  else
    args="$args $arg"
  fi
done

./format && ./detekt :apps:android:lintDebug $additional_gradle_tasks ${args:+$args}
