#!/bin/bash

additional_gradle_tasks="
:apps:shared:licensee
testDebugUnitTest
:konsist:test
"

args=""
for arg in "$@"; do
  if [ "$arg" == "--lite" ]; then
    additional_gradle_tasks=""
  else
    args="$args $arg"
  fi
done

lint_task=":apps:android:lintDevDebug"
if [ "$CI" = "true" ]; then
  lint_task=":apps:android:lintDevRelease"
fi

./format && ./gradlew detektAll $lint_task $additional_gradle_tasks ${args:+$args}
