name: Build setup
description: 'Setup the environment for building'

runs:
  using: 'composite'
  steps:
    - name: Fetch all tags
      shell: bash
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version-file: .github/.java-version

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        gradle-version: wrapper
